name: terraform-explorer

services:
  api:
    image: terraform-explorer-api
    container_name: terraform-explorer-api
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    env_file:
      - ./env/api.env
    ports:
      - "5000:5000"
    volumes:
      - ${DATA_DIR}:/app/data
      - ${WORKSPACE_DIR}:/app/workspace
    working_dir: /app
    networks:
      - terraform-explorer-network
    restart: always

  web:
    image: terraform-explorer-web
    container_name: terraform-explorer-web
    build:
      context: ../apps/web
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    env_file:
      - ./env/web.env
    ports:
      - "3000:3000"
    working_dir: /app
    depends_on:
      - api
    networks:
      - terraform-explorer-network
    restart: always

networks:
  terraform-explorer-network:
    driver: bridge
