name: Terraform Explorer - Deploy

on:
  push:
    branches:
      - main
      - release/**

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ['self-hosted', 'prod']
    environment: production
    env:
      ASPNETCORE_ENVIRONMENT: Production
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL_PRD }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN_PRD }}
      GIT_REPO_URL: ${{ secrets.GIT_REPO_URL_PRD }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME_PRD }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL_PRD }}
      CREDENTIALS_ENCRYPTION_KEY: ${{ secrets.CREDENTIALS_ENCRYPTION_KEY_PRD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Preparar envs
        run: |
          mkdir -p infra/env

          cat > infra/env/api.env <<EOF
          ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
          ASPNETCORE_URLS=http://+:5000

          TerraformSettings__RootPath=/app/workspace
          TerraformSettings__CredentialsEncryptionKey=${CREDENTIALS_ENCRYPTION_KEY}
          DatabaseSettings__ConnectionString=Data Source=/app/data/terraform.db

          GIT_TOKEN=${GIT_TOKEN}
          GIT_REPO_URL=${GIT_REPO_URL}
          GIT_USER_NAME=${GIT_USER_NAME}
          GIT_USER_EMAIL=${GIT_USER_EMAIL}
          EOF

          cat > infra/env/web.env <<EOF
          VITE_API_BASE_URL=${VITE_API_BASE_URL}
          EOF

      - name: Subir containers PROD
        run: |
          docker compose -f infra/docker-compose.yml up -d --build

  deploy-hml:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ['self-hosted', 'stg']
    environment: homologation
    env:
      ASPNETCORE_ENVIRONMENT: Development
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL_HML }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN_HML }}
      GIT_REPO_URL: ${{ secrets.GIT_REPO_URL_HML }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME_HML }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL_HML }}
      CREDENTIALS_ENCRYPTION_KEY: ${{ secrets.CREDENTIALS_ENCRYPTION_KEY_HML }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Preparar envs
        run: |
          mkdir -p infra/env

          cat > infra/env/api.env <<EOF
          ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
          ASPNETCORE_URLS=http://+:5000

          TerraformSettings__RootPath=/app/workspace
          TerraformSettings__CredentialsEncryptionKey=${CREDENTIALS_ENCRYPTION_KEY}
          DatabaseSettings__ConnectionString=Data Source=/app/data/terraform.db

          GIT_TOKEN=${GIT_TOKEN}
          GIT_REPO_URL=${GIT_REPO_URL}
          GIT_USER_NAME=${GIT_USER_NAME}
          GIT_USER_EMAIL=${GIT_USER_EMAIL}
          EOF

          cat > infra/env/web.env <<EOF
          VITE_API_BASE_URL=${VITE_API_BASE_URL}
          EOF

      - name: Subir containers HML
        run: |
          docker compose -f infra/docker-compose.yml up -d --build
